### ISSUE TITLE
Choose a Python package manager

### ISSUE THREAD

**Issue by Apexal** [personeusw18/Order-Assistant#8]
Options for dependency management include:
- pip alone
- **pipenv** [SELECTED]
- poetry
- pip-tools

**Comment by norbusonam** [comment]
@Apexal I've used standard pip and pipenv before. My vote is for pipenv.

**Comment by Apexal** [comment]
My only concern with pipenv is that it appears to be a dead project. However, it is still a common standard so let's go with it!
